services:
  - type: web
    name: dobbxbt-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CRYPTORANK_API_KEY
        sync: false
      - key: MODEL_API_KEY
        sync: false
      - key: RENDER
        value: true
